repos:
  -   repo: https://github.com/psf/black
      rev: 23.1.0  # Use the latest release, or you can specify another version
      hooks:
      -   id: black
          language_version: python3  # Optional: specify a specific Python version
